__title__ = "ComDirectStockPDFParser"
__description__ = "Parser forr comdirect stock related pdf documents to Excel "
__url__ = "https://github.com/tomerten/ComDirectStockPDFParser"
__version__ = "1.0.0.a1"
__author__ = "tm"
__license__ = "GNU General Public License v3.0"
